### ISSUE TITLE
Design scalability improvements (search)

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#867]
Design scalability improvements with input from IU and Harvard.

### T9 MAJOR ACTIVITIES (for all milestones in T9, not just this milestone)
Update Elasticsearch indices and Search API to fix current issues with scalability

### OUTCOMES (for all milestones in T9, not just this milestone)
We will refactor the Search API to improve the efficiency when the indices are being reindexed by allowing for incremental updates instead of having to replace everything as well as analyzing current procedures and improving the performance of these procedures when possible.  Additionally we analyze the number of attributes that we track to remove those that aren’t needed and move those that aren’t needed in the main index store to a secondary index. 
```[tasklist]
### Tasks
- [ ] https://github.com/hubmapconsortium/search-api/issues/781
- [ ] https://github.com/hubmapconsortium/search-api/issues/843
- [ ] https://github.com/hubmapconsortium/entity-api/issues/695
- [ ] https://github.com/hubmapconsortium/entity-api/issues/685
- [ ] https://github.com/hubmapconsortium/search-api/issues/841
- [ ] https://github.com/x-atlas-consortia/elastic-analysis/issues/1
```
